include:
  - superset/docker-compose.yml

x-restart-policy: &restart_policy
  restart: unless-stopped

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "2"

x-deploy-resources: &deploy_resources
  deploy:
    resources:
      limits:
        cpus: "4.0"
        memory: 10G

x-healthcheck: &healthcheck
  interval: 10s
  start_period: 10s
  timeout: 10s
  retries: 5

services:
  autoheal:
    <<: [*restart_policy, *logging, *deploy_resources]
    image: willfarrell/autoheal:1.2.0
    network_mode: none
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-${COMPOSE_PROJECT_NAME}
      AUTOHEAL_INTERVAL: 10
      AUTOHEAL_START_PERIOD: 300

  starrocks-fe:
    image: starrocks/fe-ubuntu:3.4.0
    hostname: ${COMPOSE_PROJECT_NAME}-starrocks-fe
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe_entrypoint.sh starrocks-fe
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Ho_Chi_Minh
    expose:
      - 8030
      - 9020
      - 9030
    networks:
      - default
    volumes:
       - app-starrocks-fe-data:/opt/starrocks/fe/meta
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "nc", "-z", "localhost", "9030"]

  starrocks-be:
    image: starrocks/be-ubuntu:3.4.0
    hostname: ${COMPOSE_PROJECT_NAME}-starrocks-be
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Ho_Chi_Minh
    expose:
      - 8040
    networks:
      - default
    depends_on:
      - starrocks-fe
    volumes:
      - app-starrocks-be-data:/opt/starrocks/be/storage
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8040"]

  mysql-client:
    image: mysql
    networks:
      - default
    depends_on:
      starrocks-fe:
        condition: service_healthy
        restart: true
      starrocks-be:
        condition: service_started
        restart: true
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "mysql -h starrocks-fe -P 9030 -u root < /init.sql"
    volumes:
      - ./mysql-client/init.sql:/init.sql
    restart: "no"

  sink-connect:
    <<: [*restart_policy, *logging, *deploy_resources]
    image: confluentinc/cp-kafka-connect:7.4.8
    hostname: ${COMPOSE_PROJECT_NAME}-sink-connect
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA__BROKER:-localhost:9092}
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_CONFIG_STORAGE_PARTITIONS: 1
      # CONNECT_CONFIG_STORAGE_CLEANUP.POLICY: compact
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_OFFSET_STORAGE_PARTITIONS: 1
      CONNECT_OFFSET_STORAGE_CLEANUP.POLICY: compact
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_STATUS_STORAGE_PARTITIONS: 1
      # CONNECT_STATUS_STORAGE_CLEANUP.POLICY: compact
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_REST_ADVERTISED_HOST_NAME: "sink-connect"
      # CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars,/connect-plugins"
      CONNECT_PLUGIN_PATH: /connect-plugins
      CONNECT_REPLICATION_FACTOR: 1
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      JAVA_OPTS: "-Xmx 2g -Xms 2g"
      CONNECT_AUTO_CREATE_TOPICS_ENABLE: “true”
      TOPIC_CREATION_ENABLE: “true”
      TOPIC_CREATION_DEFAULT_REPLICATION_FACTOR: 1
      TOPIC_CREATION_DEFAULT_PARTITIONS: 1
      TOPIC_CREATION_DEFAULT__CLEANUP_POLICY: compact
      TOPIC_CREATION_DEFAULT_COMPRESSION_TYPE: “lz4”
    volumes:
      - ./sink-connect/connect-plugins:/connect-plugins
    expose:
      - 8083
    depends_on:
      starrocks-fe:
        condition: service_healthy
        restart: true
      starrocks-be:
        condition: service_started
        restart: true
      mysql-client:
        condition: service_completed_successfully
        restart: true
    networks:
      - default

  create-connectors:
    <<: [*logging, *deploy_resources]
    image: curlimages/curl:8.11.1
    volumes:
      - ./connectors/connect-configs:/connect-configs
      - ./connectors/auto-create-connector.sh:/auto-create-connector.sh
    entrypoint: ["/bin/sh","-c"]
    command: /auto-create-connector.sh
    depends_on:
      starrocks-fe:
        condition: service_healthy
        restart: true
      starrocks-be:
        condition: service_started
        restart: true
      sink-connect:
        condition: service_started
        restart: true
      mysql-client:
        condition: service_completed_successfully
        restart: true
    networks:
      - default
    restart: "no"

  kafka-streams-app:
    build:
      context: kafka-streams
      dockerfile: Dockerfile
    hostname: ${COMPOSE_PROJECT_NAME}-kafka-streams-app
    environment:
      KAFKA_BROKER: ${KAFKA__BROKER:-localhost:9092}
    volumes:
      - app-kafka-streams-state:/tmp/kafka-streams/
    networks:
      - default

volumes:
  app-kafka-data:
  app-starrocks-data:
  app-pgadmin-data:
  app-kafka-streams-state:
  app-starrocks-fe-data:
  app-starrocks-be-data:
